import React, { createContext, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const translations = {
  English: {
    settings: 'Settings',
    settingsSubtitle: 'Manage your account, platform services, and security preferences.',
    account: 'Account',
    language: 'Language',
    theme: 'Theme',
    support: 'Support Center',
    notifications: 'Notifications',
    reports: 'Reports',
    systemHealth: 'System Health',
    securityStandards: 'Security Standards',
    privacyPolicy: 'Privacy & Policy',
    chooseLanguage: 'Select your preferred app language.',
    english: 'English',
    french: 'Français',
    back: 'Settings',
    saveChanges: 'Save changes',
    accountSaved: 'Account details saved successfully.',
    dashboardEyebrow: 'EMPLOYEE DASHBOARD',
    hello: 'Hello',
    dashboardSubtitle: 'Here is your attendance overview.',
    todaysAttendance: "Today's attendance",
    noRecordYet: 'No record yet',
    checkInNotRecorded: 'Your check-in has not been recorded.',
    attendanceRate: 'Attendance rate',
    presentDays: 'Present days',
    lateDays: 'Late days',
    absentDays: 'Absent days',
    recentActivity: 'Recent activity',
    viewAll: 'View all',
    noActivity: 'No attendance activity yet.',
    myAttendance: 'My attendance',
    attendanceSubtitle: 'Your attendance history and daily check-in record.',
    attendanceRecords: 'Attendance Records',
    records: 'records',
    date: 'Date',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    duration: 'Duration',
    status: 'Status',
    export: 'Export',
    all: 'All',
    present: 'Present',
    late: 'Late',
    absent: 'Absent',
    noRecords: 'No records found',
    noRecordsPeriod: 'There are no records for this period.',
    profile: 'Profile',
    available: 'Available',
    contactInfo: 'Contact info',
    email: 'Email',
    phone: 'Phone',
    department: 'Department',
    about: 'About',
    position: 'Position',
    employeeId: 'Employee ID',
    changeProfilePicture: 'Change profile picture',
    welcomeBack: 'Welcome back',
    credentialsSubtitle: 'Enter your credentials to access your account',
    emailAddress: 'Email Address',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    agreeTerms: 'I agree to the Terms & Policies',
    forgotTitle: 'Forgot your password?',
    forgotSubtitle: "Enter your email address and we'll send you a verification code.",
    continue: 'Continue',
    verify: 'Verify',
    verifyIdentity: 'Verify your identity',
    verifySubtitle: 'We sent a 5-digit code to your email. Enter it below to continue.',
    verifyCode: 'Verify code',
    resendCode: 'Resend code',
    createPassword: 'Create a new password',
    newPasswordSubtitle: 'Choose a strong password to keep your account secure.',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    createPasswordButton: 'Create password',
    passwordSuccess: 'Password created successfully',
    passwordSuccessSubtitle: 'Your password has been updated. You can now sign in with your new password.',
    continueSignIn: 'Continue to sign in',
    operationalOverview: 'Operational Overview',
    operationalSubtitle: 'Real-time monitoring of Presenza facilities. Tracking attendance, security checkpoints, and employee movement across global sectors.',
    last30Days: 'Last 30 Days',
    exportData: 'Export Data',
    totalEmployees: 'Total Employees',
    averageAttendance: 'Avg. Attendance',
    activeLocations: 'Active Locations',
    pendingAlerts: 'Pending Alerts',
    methodOfEntry: 'Method of Entry',
    securityInsights: 'Security Insights',
    securitySubtitle: 'A quick view of security activity across your facilities',
    securityAlerts: 'Security alerts',
    unreadAlerts: 'Unread alerts require administrator review',
    lateCheckIns: 'Late check-ins',
    lateRecords: 'Attendance records marked late',
    verifiedAttendance: 'Verified attendance',
    verifiedRecords: 'Present records successfully verified',
    liveFeed: 'Live Attendance Feed',
    searchAttendance: 'Search attendance...',
    filter: 'Filter',
    noMatchingAttendance: 'No attendance records match this filter.',
    complianceSnapshot: 'Compliance Snapshot',
    verificationAccuracy: 'Verification Accuracy',
    verifiedAttendanceRecords: 'Verified attendance records',
    averageResponse: 'Average Response Time',
    averageVerification: 'Average verification response',
    deeperInsight: 'Need deeper insight?',
    reportBuilder: 'Open Report Builder',
    apiDocumentation: 'API Documentation',
    operations: '2026 Attendance Operations',
    professionalStandards: 'Professional-grade security and operational standards',
    securityPolicy: 'Security Policy',
    dashboard: 'Dashboard',
    employees: 'Employees',
    attendance: 'Attendance',
    settingsTab: 'Settings',
    profileTab: 'Profile',
  },
  French: {
    settings: 'Paramètres',
    settingsSubtitle: 'Gérez votre compte, les services et les préférences de sécurité.',
    account: 'Compte',
    language: 'Langue',
    theme: 'Thème',
    support: 'Centre d’assistance',
    notifications: 'Notifications',
    reports: 'Rapports',
    systemHealth: 'État du système',
    securityStandards: 'Normes de sécurité',
    privacyPolicy: 'Confidentialité et politique',
    chooseLanguage: 'Sélectionnez la langue de votre application.',
    english: 'English',
    french: 'Français',
    back: 'Paramètres',
    saveChanges: 'Enregistrer',
    accountSaved: 'Les informations du compte ont été enregistrées.',
    dashboardEyebrow: 'TABLEAU DE BORD EMPLOYÉ',
    hello: 'Bonjour',
    dashboardSubtitle: 'Voici votre aperçu des présences.',
    todaysAttendance: 'Présence du jour',
    noRecordYet: 'Aucun enregistrement',
    checkInNotRecorded: 'Votre arrivée n’a pas encore été enregistrée.',
    attendanceRate: 'Taux de présence',
    presentDays: 'Jours présents',
    lateDays: 'Jours en retard',
    absentDays: 'Jours absents',
    recentActivity: 'Activité récente',
    viewAll: 'Voir tout',
    noActivity: 'Aucune activité de présence.',
    myAttendance: 'Ma présence',
    attendanceSubtitle: 'Votre historique de présence et vos enregistrements quotidiens.',
    attendanceRecords: 'Enregistrements de présence',
    records: 'enregistrements',
    date: 'Date',
    checkIn: 'Arrivée',
    checkOut: 'Départ',
    duration: 'Durée',
    status: 'Statut',
    export: 'Exporter',
    all: 'Tous',
    present: 'Présent',
    late: 'En retard',
    absent: 'Absent',
    noRecords: 'Aucun enregistrement',
    noRecordsPeriod: 'Aucun enregistrement pour cette période.',
    profile: 'Profil',
    available: 'Disponible',
    contactInfo: 'Coordonnées',
    email: 'E-mail',
    phone: 'Téléphone',
    department: 'Département',
    about: 'À propos',
    position: 'Poste',
    employeeId: 'Identifiant employé',
    changeProfilePicture: 'Changer la photo de profil',
    welcomeBack: 'Bon retour',
    credentialsSubtitle: 'Saisissez vos identifiants pour accéder à votre compte',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    signIn: 'Se connecter',
    agreeTerms: "J’accepte les conditions d’utilisation",
    forgotTitle: 'Mot de passe oublié ?',
    forgotSubtitle: 'Saisissez votre adresse e-mail et nous vous enverrons un code de vérification.',
    continue: 'Continuer',
    verify: 'Vérifier',
    verifyIdentity: 'Vérifiez votre identité',
    verifySubtitle: 'Nous avons envoyé un code à 5 chiffres à votre adresse e-mail. Saisissez-le pour continuer.',
    verifyCode: 'Vérifier le code',
    resendCode: 'Renvoyer le code',
    createPassword: 'Créer un nouveau mot de passe',
    newPasswordSubtitle: 'Choisissez un mot de passe fort pour sécuriser votre compte.',
    newPassword: 'Nouveau mot de passe',
    confirmNewPassword: 'Confirmer le nouveau mot de passe',
    createPasswordButton: 'Créer le mot de passe',
    passwordSuccess: 'Mot de passe créé avec succès',
    passwordSuccessSubtitle: 'Votre mot de passe a été mis à jour. Vous pouvez maintenant vous connecter.',
    continueSignIn: 'Continuer vers la connexion',
    operationalOverview: 'Aperçu opérationnel',
    operationalSubtitle: 'Surveillance en temps réel des installations Presenza. Suivi des présences, des points de contrôle et des mouvements des employés.',
    last30Days: '30 derniers jours',
    exportData: 'Exporter les données',
    totalEmployees: 'Total des employés',
    averageAttendance: 'Présence moyenne',
    activeLocations: 'Sites actifs',
    pendingAlerts: 'Alertes en attente',
    methodOfEntry: 'Méthode d’accès',
    securityInsights: 'Informations de sécurité',
    securitySubtitle: 'Aperçu rapide de l’activité de sécurité dans vos installations',
    securityAlerts: 'Alertes de sécurité',
    unreadAlerts: 'Les alertes non lues nécessitent un examen administratif',
    lateCheckIns: 'Arrivées en retard',
    lateRecords: 'Enregistrements de présence marqués en retard',
    verifiedAttendance: 'Présences vérifiées',
    verifiedRecords: 'Enregistrements présents vérifiés avec succès',
    liveFeed: 'Flux des présences en direct',
    searchAttendance: 'Rechercher une présence...',
    filter: 'Filtrer',
    noMatchingAttendance: 'Aucun enregistrement ne correspond à ce filtre.',
    complianceSnapshot: 'Aperçu de conformité',
    verificationAccuracy: 'Précision de vérification',
    verifiedAttendanceRecords: 'Enregistrements de présence vérifiés',
    averageResponse: 'Temps de réponse moyen',
    averageVerification: 'Réponse moyenne de vérification',
    deeperInsight: 'Besoin d’une analyse approfondie ?',
    reportBuilder: 'Ouvrir le générateur de rapports',
    apiDocumentation: 'Documentation API',
    operations: 'Opérations de présence 2026',
    professionalStandards: 'Normes professionnelles de sécurité et d’exploitation',
    securityPolicy: 'Politique de sécurité',
    dashboard: 'Tableau de bord',
    employees: 'Employés',
    attendance: 'Présence',
    settingsTab: 'Paramètres',
    profileTab: 'Profil',
  },
};

const LanguageContext = createContext({ language: 'English', setLanguage: () => {}, t: key => translations.English[key] || key });

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState('English');

  useEffect(() => {
    AsyncStorage.getItem('Presenza_language').then(savedLanguage => {
      if (savedLanguage === 'English' || savedLanguage === 'French') setLanguageState(savedLanguage);
    });
  }, []);

  const setLanguage = async value => {
    setLanguageState(value);
    await AsyncStorage.setItem('Presenza_language', value);
  };

  const t = key => translations[language][key] || translations.English[key] || key;

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
